### ISSUE TITLE
Prevent a specific category from being updated automatically 

### ISSUE THREAD

**Issue by leewdch** [inorichi/tachiyomi#1318]
**App version:** 0.7.0

**Issue/Request:** Add a way to filter out a specific category if you tap twice in the list for automatic updates. It's the same thing you use for manga filters (red cross). If you leave all categories blank it automatically defaults to "update everything".

**Comment by LakotaGray** [comment]
Can’t you select which categories TO update and it won’t do the ones not selected? If you add the red x option, then what does it do for the unselected boxes? You’re saying to put check mark for those to update, red x for no update but then categories with no mark what happens? Just select the ones you want to update and leave those you don’t wish to update unmarked

**Comment by inorichi** [comment]
What @LakotaGray said.

**Comment by wopian** [comment]
Make a category "Reading" and set it as your default category for added manga

**Comment by leewdch** [comment]
This solves the issue for now, but this behavior should be fixed so that somebody can just use the Default category for reading titles. Specifically answering to what @LakotaGray said:

> Can’t you select which categories TO update and it won’t do the ones not selected?

No because I'm using categories to exclude titles I don't want to update.

> If you add the red x option, then what does it do for the unselected boxes?

It let me exclude titles I don't want to update, otherwise I need to make an additional category doing the same job of the Default one. This redundancy should be fixed, not bypassed

> You’re saying to put check mark for those to update, red x for no update but then categories with no mark what happens?

You can use three types of check marks then, a ✓ to manually update a title, a ❌to ignore a title and a ▣ for untouched titles meaning that whatever has this symbol is automatically update by default since  this is the default behavior. This feels indeed redundant as well but the other way is making the update list an ignore list so that whatever is checked in the list is ignored and the app just automatically updates everything that has not a mark in the list

> Just select the ones you want to update and leave those you don’t wish to update unmarked

Issue is that I don't want to update my other categories, I want to ignore them

**Comment by paulo27ms** [comment]
It's more like, Tachiyomi should have the option to update the Default category.
I personally have an "All" category which is basically the same as the Default so I never even thought this was an issue.
The suggestion still doesn't feel needed (what I mentioned should definitely be revised though).

**Comment by leewdch** [comment]
> It's more like, Tachiyomi should have the option to update the Default category.

meaning that it automatically updates only the Default category, not every category? if that's what you mean then I feel the same. this solves my issue and let me use the already existing update list to leave categories I don't want to update un-marked

**Comment by paulo27ms** [comment]
Yes, the Default category should be recognized as any other category. Users can easily bypass this by simply creating a category and they can consider that the "Default" like I do but I don't see the benefit of currently not recognizing Default as any other category.

**Comment by leewdch** [comment]
I don't want to make the Default category a non-category, I want to prevent the default behavior of tachiyomi from updating my other categories. if the solution to this request is a workaround it just means that there is room for improvement

**Comment by LakotaGray** [comment]
You know both ways to update categories right? There’s the global update, which will update all categories UNLESS excluded in settings function. 
AND
Category specific updates where from the library screen,  be in which ever category you want to update, and pull down until the circle spins. That will update ONLY the selected category. So you won’t have to do all categories.

**Comment by leewdch** [comment]
This is good but how do I prevent the app from automatically updating all the categories? Because that's what is happening, as you can see from my screenshots

**Comment by LakotaGray** [comment]
Either change the updates setting to include only the categories you want, (maybe make another category for the stuff you have in default because default is GONNA update). 
OR
Do category specific updates one by one. Enter library  —> select category to be updated—> middle of screen press and hold while pulling down. The update will only update that category

**Comment by leewdch** [comment]
The problem here is that the default behavior of the app is to update every category no matter what, to prevent this you need to pick a category from the list to "include" in the updates so that the app finally ignores the unpicked categories. I'd update the categories manually if the app would stop updating them automatically

**Comment by LakotaGray** [comment]
Why would keep it set for auto updating  then? Settings —> General —> Library Update Frequency —> Manual. This settings value leaves it completely up to you to update your library series. Although if you have it set as such, and press the circular arrow from any category it’ll still do a whole library update. But by having Manual set, and then pulling down from within any specific category, only that category updates. It sounds like this would solve your issue.

**Comment by leewdch** [comment]
But I want my titles in Default to still be updated automatically. On the other hand I want my other categories to just stop updating automatically..

**Comment by LakotaGray** [comment]
Then change your “default” category to a separate category, like “update”. You can then have it set to auto, while others don’t. It seems you’re wanting something coded and set as a new deafault behavior when it’s a very specific set of curcumstances needed to make it applicable. There are several relatively easy ways to have it set up like you want, but you seem uninterested in any answer but to change the deauflt setting of app
