### ISSUE TITLE
[Feature Request] Chapter size

### ISSUE THREAD

**Issue by Fahad1998** [inorichi/tachiyomi#2111]
Any plan on showing chapter size when downloading?

**Comment by CarlosEsco** [comment]
No?

**Comment by Fahad1998** [comment]
why? at least something like an estimation.

**Comment by CarlosEsco** [comment]
estimate of the size of the download?

**Comment by Fahad1998** [comment]
yeah. like a chapter has 20 files after downloading 1 file checking its size and multiply it with 20. then after downloading one more file sum 1st and 2nd files size then divide with 2 and multiply with 20. and so on.

**Comment by eshanrh** [comment]
If the first page is a double page, it will be bigger and then the whole estimation will be skewed, leading to providing very wrong information to the user early on, and less wrong information after a few more pages have downloaded. 

I don't think that it's worth implementing, especially since it misleads the user

**Comment by CarlosEsco** [comment]
its not.  a download takes < 1minute for most sources.

**Comment by Fahad1998** [comment]
After downloading store the size of all images in chapter list. This way we can guess the size of other chapters.

**Comment by arkon** [comment]
You'll end up with the famously inconsistent progress bars from Windows if you do something like that.

At best, you could make some requests and potentially get filesizes from the response headers, but that seems overkill.

**Comment by Fahad1998** [comment]
no i mean the user can guess. not the app trying to guess itself

**Comment by Fahad1998** [comment]
something like this
https://i.ibb.co/jr9bjQr/Screenshot-20190702-194212-eu-kanade-tachiyomi.jpg

**Comment by eshanrh** [comment]
Wait so you're not asking for chapter size DURING download, but chapter size AFTER download. That changes the issue completely, I think it may be feasible.

**Comment by Fahad1998** [comment]
The main think is to know the chapter size for this source and manga. Different sources use different quality same manga chapter can be 1mb in a source and 17mb in other. so what i want to guess is size of chapter from this source and manga.

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi/issues/1305

**Comment by Fahad1998** [comment]
ok. So i implemented it and this is what its looks like
https://i.ibb.co/25RqKVt/Screenshot-20190703-225432-eu-kanade-tachiyomi.jpg

**Comment by hXtreme** [comment]
Can you make it an opt in thing. I personally don't want it shown, partly because it doesn't look good to me and partly because it doesn't improve my overall experience with the download process.

Regardless of how big a chapter is, if I want to read it, I'll download it the additional information doesn't do anything for me. For me, even an inaccurate ETA is more useful as it allows me to decide if I should wait for the download and then run to catch the train or should I just go for the train now.

**Comment by Efreak** [comment]
I don't much care about estimated time to download, however it'd be useful to know how fast Tachiyomi is downloading data, and it would also be useful to know how much space each chapter takes up.

I can see that others would be interested in time to completion, however it might be better to simply state how long the task/chapter has been running for, and how many pages/percent completion; this way you can still make guesses about how much longer it will be, and can't complain about accuracy.

**Comment by eshanrh** [comment]
@Efreak 

How does download speed make a difference? 
It might be helpful to know how much space each chapter takes up after downloading, but how would we display this? It would look nasty to have the file size under every chapter. 

I agree with the timed downloads, it seems like clever idea. This way the user can see "oh this has been running for 5 minutes and we're still not even half way, this is going to be too slow". We already have a pages completed indicator.

**Comment by arkon** [comment]
I'm just going to veto this. ¯\\\_(ツ)_/¯
