### ISSUE TITLE
Problem manga (only kissmanaga)

### ISSUE THREAD

**Issue by Snake87r** [inorichi/tachiyomi#696]
Hello,
Today i tried to open a manga chapter and when i opened it a toast appear and show "Page list is empty"..I tried to clear cache etc and after some test i found out that the problem is on manga added throught kissmanga..

Version: r1109 or v0.0.0
(Android 7.0 Sony Z4 tablet)

**Comment by inorichi** [comment]
It happens sometimes, msot probably cloudflare things. Try restarting router, opening kissmanga in browser, clear cookies and maybe wait a day or two.

**Comment by Snake87r** [comment]
Normally I use vdsl connection, i switched to mobile connection throught tethering and the app works fine.. 
After 1 day i returned back to vdsl connection (without rebooting the router) and the problem is solved..

**Comment by namack75** [comment]
actually, I think KissManga added a Captcha check before rendering the chapter.

**Comment by jedinat** [comment]
Same issue here

**Comment by inorichi** [comment]
They've encrypted the image urls. I don't know if I'll be able to workaround that.

**Comment by GreyAsteroid** [comment]
Check out https://github.com/Twoure/KissNetwork.bundle/issues/53 for a fix, it's the same encryption used by all their other sites.

**Comment by inorichi** [comment]
There should be a new release with a fix soon.

**Comment by inorichi** [comment]
Fixed in v0.5.1

**Comment by Ligerx** [comment]
I'm still running into the Page List is empty bug even after updating to 5.1

I can try debugging the issue more in a couple hours.

**Comment by inorichi** [comment]
That should be the anti-bot check. It would help if you can debug it to confirm.

**Comment by Ligerx** [comment]
Still does not seem to work. Here's what I tried.

1. Trying to open the latest Fairy Tail chapter, but it shows the empty page list
2. In Chrome, I go to Kissmanga, pass the recaptcha, and start reading a couple pages of the Fairy Tail chapter above
3. Kill the Tachiyomi app, restart it, refresh the chapter listing for Fairy Tail.
4. When I click on the latest Fairy Tail chapter, I still get the empty page list error

**Comment by jedinat** [comment]
The fix worked for me

**Comment by Ligerx** [comment]
Looking at another issue, clearing the chapter cache fixed the problem for me!

**Comment by chalermla24** [comment]
The problem still persist for me. Also when I enter KissManga website with different browser on my phone, each one of them will have that CloudFlare page when I loaded it the first time. Maybe the app doesn't pass the CloudFlare page?
